### ISSUE TITLE
Error When Using Extensions Override Service

### ISSUE THREAD

**Issue by cemalgnlts** [CodinGame/monaco-vscode-api#296]
Hi,

There is an error when using this service with arguments:
```js
await initialize({
  ...getDefaultExtensionOverride(workerConfig),
});
```

![Screenshot 2023-12-09 21 26 16](https://github.com/CodinGame/monaco-vscode-api/assets/45357531/958f297e-ae5c-44b2-82f2-48bb09155805)

I created a project that only uses this package to see the error: https://stackblitz.com/edit/stackblitz-starters-sc18an

**Comment by CompuIves** [comment]
Hey! I've seen this error before, in my case it was happening because the extension host web worker could not be loaded. That was happening because it could not load `vscode-semver`, it was not properly deduplicated. I fixed it my adding `"vscode-semver": "npm:semver@5.5.0"` to the dependencies in package.json. Does that work for you?

**Comment by cemalgnlts** [comment]
Unfortunately, it did not solve the problem. Worker is running but for some reason it stops suddenly and I can't understand what's going on because it doesn't give me an error message.

[Screen recording 2023-12-13 11.32.04.webm](https://github.com/CodinGame/monaco-vscode-api/assets/45357531/f602fc55-0006-477b-a58a-afab7844e176)

**Comment by CompuIves** [comment]
Yeah, that was a huge challenge for me as well at the time. Had to change the code to `await` import statements instead. Can you reproduce the same problem locally? Maybe WebContainers does some magic to support web workers and it isn't compatible with how we load them.

**Comment by cemalgnlts** [comment]
I got the error when running in local and started playing with the demo of the library.

That was the line that solved my problem:
```diff
optimizeDeps: {
+   include: ["vscode-semver"]
...
}
```

However, my example in WebContainer was giving an error even though I did this. This time I added the method you suggested:
```diff
dependencies: {
+  "vscode-semver": "npm:semver@5.5.0"
}
```

When I do both configurations: It's fully functional now.

**Thanks.**
*(Although it took me 1 week, I'm glad it was solved.)*
