### ISSUE TITLE
typescript standalone workers not being disposed correctly

### ISSUE THREAD

**Issue by rubenfiszel** [CodinGame/monaco-vscode-api#629]
After upgrading to a later version of monaco-vscode-api. It seems that typescript workers are not being disposed correctly.

The debugger shows that this line is being called correctly: https://github.com/microsoft/monaco-editor/blob/main/src/language/typescript/workerManager.ts#L39 but still the typescript worker is not disposed and occupy a pretty staggering 150Mb of memory per invocation.

It's a very critical issue for us as we made releases on windmill already with this bug.

![Image](https://github.com/user-attachments/assets/c0fa77e6-ccee-4e92-99a7-3ff58e50e397)

You can see multiple worker.js instance taking each 150Mb

1) How come it takes 150Mb of memory. Is that normal
2) Why are they not disposed correctly

The worker that is passed is:

```
			typescript: () => {
				return new Worker(
					new URL(
						'@codingame/monaco-vscode-standalone-typescript-language-features/worker',
						import.meta.url
					),
					{
						type: 'module'
					}
				)
			},
```

**Comment by CGNonofr** [comment]
I'm not sure I understand 🤔 when are workers supposed to be disposed?

**Comment by rubenfiszel** [comment]
@CGNonofr the workers are supposed to be disposed when we create new ones and we create new ones as we spawn new editors.

The dispose() is called correctly, but the memory and workers are not actually disposed

**Comment by CGNonofr** [comment]
Are you using the very last version? a fix was merged regarding setExtraLib this week

**Comment by rubenfiszel** [comment]
Thanks, it seems to indeed fix setExtraLib. I will find a way to dirty inject the fix as a postinstall but would be very grateful for clean solution @kaisalmen 

@CGNonofr I think the issue still stand, the worker being disposed is not actually freeing memory (that may be the same with monaco-editor, didn't have time to test)
And the typescript worker seems to take 130MB which seems much more than with the vanilla monaco-editor but haven't done thorough comparison yet
